---

- name: "Load our wordpress vars into memory from {{ inventory_dir }}/group_vars/wordpress.yml"
  include_vars:
    file: "{{ inventory_dir }}/group_vars/wordpress.yml"

- name: Get all wordpress hosts into an in memory group
  set_fact:
    wordpress_hosts: "{{ groups[vpc_name + '_wordpress'] }}"


- name: Get latest wp-contents/uploads data
  git:
    clone: yes
    depth: 1
    dest: "{{ playbook_dir }}/uploads-content"
    repo: "git@gitlab.service.opg.digital:sirius/help-and-guidance-content.git"
    version: "master"
    accept_hostkey: yes

- name: "Sync data with the wordpress instances (direction {{ sync_action }})"
  include: "{{ sync_action }}.yml"

- block:
    - name: Stop docker-compose services
      shell: "docker-compose -f /etc/docker-compose/wordpress/docker-compose.yml down || true"
      delegate_to: "{{ item }}"
      with_items: "{{ wordpress_hosts }}"
      become: true

    - name: Start docker-compose services
      shell: "docker-compose -f /etc/docker-compose/wordpress/docker-compose.yml up -d"
      delegate_to: "{{ item }}"
      with_items: "{{ wordpress_hosts }}"
      become: true
  when: restart_docker is defined and restart_docker

- name: Remove upload-contents from local
  file:
    path: "{{ playbook_dir }}/uploads-content"
    state: absent
  delegate_to: localhost
