---

- hosts: "{{ target }}"

- name: Load our config defaults
  include_vars:
    file: defaults.yml

- block:
    - name: Merge our metadata with our config
      set_fact:
        collectd_settings: "{{ collectd_settings | update(collectd) }}"
    when: collectd is defined

- name: Ensure service is installed and running
  include: "service.yml"

- name: Copy config files for plugins
  include: "plugins.yml"

