---

- hosts: "{{ target }}"

- name: Load our config defaults
  include_vars:
    file: defaults.yml

- name: Ensure service is installed and running
  include: "service.yml"

- name: Copy config files for plugins
  include: "plugins.yml"

