---

- name: Copy collectd config files to remote
  copy:
    src: "{{ item }}.conf"
    dest: "/usr/share/collectd/modules/{{ item }}.conf"
    owner: root
    group: root
    mode: 0755
  with_items:
    - collectd
    - ntpd
    - python
    - syslog
    - write_graphite
