---

- name: "Set ASG desired instance counts"
  ec2_asg:
    name: "{{ asg_name }}"
    min_size: "{{ asg_min }}"
    max_size: "{{ asg_max }}"
    desired_capacity: "{{ asg_desired }}"
    launch_config_name: "{{ lc_name }}"
    wait_for_instances: "{{ wait_for_instances|default(True) }}"