---

- name: Create fifo dead letter queue resources
  command: aws sqs create-queue --queue-name "{{ sqs_dead_letter_queue.name }}.fifo" --attributes file://queue_attributes.json

- name: Create fifo SQS queue resources
  command: aws sqs create-queue --queue-name "{{ sqs_queue.name }}.fifo" --attributes file://queue_attributes.json
