---

- name: Create fifo dead letter queue resources
  command: aws sqs create-queue --queue-name "{{ sqs_dead_letter_queue.name }}.fifo" --attributes {{ sqs_dead_letter_queue.attributes }}

- name: Check the existence of our fifo dead letter queue
  command: aws sqs list-queues --queue-name-prefix "{{ sqs_dead_letter_queue.name }}.fifo"
  register: dead_letter_queue_exists
  ignore_errors: True

- name: Create fifo SQS queue resources
  command: aws sqs create-queue --queue-name "{{ sqs_queue.name }}.fifo" --attributes {{ sqs_queue.attributes }}
  when:
          - dead_letter_queue_exists.stderr|trim|length > 1

- name: Check the existence of our fifo queue
  command: aws sqs list-queues --queue-name-prefix "{{sqs_queue.name}}.fifo"
  register: queue_exists
  ignore_errors: True

- name: Just to move on # a different step here?
  command: aws sqs list-queues --queue-name-prefix "{{sqs_queue.name}}.fifo"
  when:
          - queue_exists.stderr|trim|length > 1
