---

- block:
    - name: install specified bash version
      apt:
        name: "bash={{ bash_version }}"
        state: present

  when: bash_version is defined

- name: Install bash hardening script
  copy:
    src: bash_hardening.sh
    dest: etc/profile.d/bash_hardening.sh
    mode: 0644
