---

- name: Update sshd config file
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config

- name: ensure that sshd is enabled and running
  service:
    name: sshd
    state: running
    enabled: yes

- block:
    - name: Ensure root access is single terminal only
      file:
        dest: /etc/securetty
        mode: 0600
        state: touch
  when: use_secure_tty is defined