---

- block:
    - name: Create cron job
      cron:
        name: "{{ job.name }}"
        hour: "{{ job.hour | d('*') }}"
        minute: "{{ job.minute | d('*') }}"
        day: "{{ job.daymonth | d('*') }}"
        month: "{{ job.month | d('*') }}"
        weekday: "{{ job.dayweek | d('*') }}"
        job: "{{ job.command }}"
        user: "{{ job.user }}"
        state: present
      become: true
  when: job.enabled

- block:
    - name: Remove cron job
      cron:
        name: "{{ cron_name }}"
        user: "{{ job.user }}"
        state: absent
      become: true
  when: job.enabled is false
