---

- name: Create our temporary dead letter queue attributes file
  template:
    src: dead_letter_queue_attributes.j2.json
    dest: "{{ playbook_dir }}/dead_letter_queue_attributes.json"
  delegate_to: localhost

- name: Create fifo dead letter queue resources
  command: aws sqs create-queue --queue-name "{{ sqs_dead_letter_queue.name }}.fifo" --attributes file://{{ playbook_dir }}/dead_letter_queue_attributes.json

- name: Check the existence of our fifo dead letter queue
  shell: "aws sqs list-queues --queue-name-prefix {{ sqs_dead_letter_queue.name }}.fifo | grep {{ sqs_dead_letter_queue.name }}.fifo"
  register: dead_letter_queue_exists
  until: dead_letter_queue_exists.rc == 0
  retries: 6
  delay: 1
  
- name: Create our temporary queue attributes file
  template:
    src: queue_attributes.j2.json
    dest: "{{ playbook_dir }}/queue_attributes.json"
  delegate_to: localhost

- name: Create fifo SQS queue resources
  command: aws sqs create-queue --queue-name "{{ sqs_queue.name }}.fifo" --attributes file://{{ playbook_dir }}/queue_attributes.json

- name: Check the existence of our fifo queue
  shell: "aws sqs list-queues --queue-name-prefix {{sqs_queue.name}}.fifo  | grep {{ sqs_queue.name }}.fifo"
  register: queue_exists
  until: dead_letter_queue_exists.rc == 0
  retries: 6
  delay: 1
