---
- name: List SQS Dead Letter Queues
  command: aws sqs list-queues --queue-name-prefix "{{ sqs_dead_letter_queue.name }}.fifo"
  set_fact:
    queue_to_remove: "{{ command_output.stdout }}"

- name: Destroy fifo SQS queue resources
  command: aws sqs delete-queue --queue-url "{{ queue_to_remove }}"

- name: List SQS Queues
  command: aws sqs list-queues --queue-name-prefix "{{sqs_queue.name}}.fifo"
  set_fact:
    dead_letter_queue_to_remove: "{{ command_output.stdout }}"

- name: Destroy fifo SQS queue resources
  command: aws sqs delete-queue --queue-url "{{ dead_letter_queue_to_remove }}"
