---

- name: Set bucket name (no suffix)
  set_fact:
    bucket_name: "{{ bucket_data.name }}"
  when:  use_s3_suffix is not defined or not use_s3_suffix

- name: Set bucket name (with suffix)
  set_fact:
    bucket_name: "{{ bucket_data.name }}-{{ opg_data.stack }}"
  when:  use_s3_suffix is defined and use_s3_suffix

- name: Display bucketname message
  debug:
    msg: "Creating S3 bucket {{bucket_name}}"

- name: Set bucket policy string
  set_fact:
    bucket_policy_string:  "{{ lookup('template', bucket_data.policy) | to_json }}"
  when: "'policy' in bucket_data"

- name: Create S3 buckets with policy
  s3_bucket:
    name: "{{ bucket_name }}"
    state: present
    policy: "{{ bucket_policy_string | default(omit) }}"
    versioning: "{{ bucket_data.versioning | default(false)}}"
    tags:
      stack: "{{ opg_data.stack }}"
      # MOJ required tags
      application: "{{ opg_data.application | default('None Specified') }}"
      business-unit: "{{ opg_data.business_unit | default('None Specified') }}"
      component: "{{ opg_data.component | default('None Specified') }}"
      environment-name: "{{ opg_data.environment | default('None Specified') }}"
      infrastructure-support: "{{ opg_data.infrastructure_support | default('None Specified') }}"
      is-production: "{{ opg_data.is_production | default('None Specified') }}"
      owner: "{{ opg_data.owner | default('None Specified') }}"
      runbook: "{{ opg_data.runbook | default('None Specified') }}"
      source-code: "{{ opg_data.source_code | default('None Specified') }}"
  register: s3_bucket_created

- name: Set non current version expiration
  command: "aws s3api put-bucket-lifecycle-configuration  \
            --bucket {{ bucket_name }}  \
            --lifecycle-configuration file://lifecycle.json "
  when: "'lifecycle' in bucket_data and 'non_current_version_expiration' in bucket_data.lifecycle"

- name: Encrypt bucket with KMS key
  include: bucket-encryption-kms.yml
  when: "'default_encryption_kms_keyname' in bucket_data"
