---

- name: Set clusters
  set_fact:
    ecs_clusters: "{{ app_data|rejectattr('ecs_cluster', 'undefined')|map(attribute='ecs_cluster')|list|unique }}"

- name: Set typed app
  set_fact:
    typed_apps: "{{ app_data|rejectattr('type', 'undefined')|list }}"

- name: Create ECS apps
  include: ecs.yml
  with_items: "{{ typed_apps|selectattr('type','match','ecs')|list }}"
  when: typed_apps is defined
  loop_control:
    loop_var: appdata
  tags:
    - ecs
