---
- name: Create iam role for ecs service
  iam:
    iam_type: role
    name: "{{ appdata.name }}.{{ target }}"
    state: present
    trust_policy:
      Version: "2012-10-17"
      Statement:
      - Action: "sts:AssumeRole"
        Effect: Allow
        Principal:
          Service: "ecs.amazonaws.com"
  register: iam_ecs_role

- name: Create iam policies
  iam_policy:
    state: present
    policy_name: "{{ appdata.name }}-{{ target }}"
    iam_name: "{{ appdata.name }}.{{ target }}"
    iam_type: role
    policy_json: " {{ lookup('template', 'iam_policy_ecs_task.json') }} "

- name: Wait for policies to settle
  pause:
    minutes: 1
