---

- name: Get account id data
  # This can be hard coded for local runs i.e. shell: "echo <the target account id>"
  shell: "aws sts get-caller-identity | grep -Po '(?<=\"Account\": \").*?(?=\",)'"
  register: account_id
  check_mode: no
  no_log: true
  changed_when: false
  tags:
    - always

- name: Make accountid value available
  set_fact:
    aws_acc_id: "{{ account_id.stdout }}"
  check_mode: no
  no_log: true
  changed_when: false
  tags:
    - always
