---

- name: Gather account level facts
  include: account-facts.yml
  tags:
    - always

- name: Gather vpc level facts
  include: vpc-facts.yml
  tags:
    - always

- name: Gather instances into runtime groups
  include: inventory-groups.yml
  tags:
    - always

- name: Gather hosted zone facts
  include: zone-facts.yml
  tags:
    - always

- name: Gather metadata facts
  include: metadata-facts.yml
  tags:
    - always
