---

- name: Gather account level facts
  include: account.yml
  tags:
    - always

- name: Gather vpc level facts
  include: vpc.yml
  tags:
    - always

- name: Gather instances into runtime groups
  include: groups.yml
  tags:
    - always

- name: Gather hosted zone facts
  include: zones.yml
  tags:
    - always

- name: Gather metadata facts
  include: metadata.yml
  tags:
    - always
