---

- name: Gather account level facts
  include: account
  tags:
    - always

- name: Gather vpc level facts
  include: vpc
  tags:
    - always

- name: Gather instances into runtime groups
  include: groups
  tags:
    - always

- name: Gather hosted zone facts
  include: zones
  tags:
    - always
