---

- name: Retrieve vpc level instance facts
  ec2_remote_facts:
    filters:
      instance-state-name: running
      "tag:Stack": "{{ vpc_name }}"
  register: vpc_instance_facts
  tags:
    - always
