---

# From bootstrap, is this still needed

- name: Run apt update
  apt:
    update_cache: yes

- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - joe
    - git
    - awscli
