nginx:
  build: .
  ports:
  - 80:80
  - 443:443
  environment:
  - OPG_NGINX_SSL_FORCE_REDIRECT=1
  - OPG_NGINX_SERVER_NAMES={{ lookup('env','OPG_DOMAIN') }} *.{{ lookup('env','OPG_DOMAIN') }} *.{{ lookup('env','OPG_STACKNAME') }}.internal {{ hostvars[inventory_hostname].ansible_default_ipv4.address|string }} {{ salt['grains.get']('ip4_interfaces:docker0:0')|string }} localhost 127.0.0.1