---

- block:
    - name: Configure docker registry access
      copy:
        dest: /root/.dockercfg
        owner: root
        group: root
        content: "{{ docker.docker-registries | to_json }}"
        hosts: "{{ target }}"

  when: docker.docker-registries is defined
