---

- name: Ensure monitoring_client directory exists
  file:
    state: directory
    path: "/etc/docker-compose/{{ client_data.name|default('monitoring_client') }}"
    owner: root
  become: true

- name: Create our list to hold our env_file names
  set_fact:
    env_file_names: []

- block:
    - name: Extract our list of env_file names
      set_fact:
        env_file_names: "{{ env_file_names + [ item.name ] }}"
      with_items: "{{ client_data.env_files }}"
  when: client_data.env_files|default(False)

- block:
    - name: Extract out target specific env files
      set_fact:
        env_file_names: "{{ env_file_names + [ item.name ] }}"
      with_items: "{{ client_data.extra }}"
      when: item.name | search("_{{ opg_role }}$")

- name: Create compose service file
  template:
    src: "{{ client_data.docker_compose_template }}"
    dest: "/etc/docker-compose/{{ client_data.name|default('monitoring_client') }}/docker-compose.yml"
    owner: root
  become: true

- name: Add systemd service
  template:
    src: "docker-compose-service-systemd.j2"
    dest: "/etc/systemd/docker-compose-monitoring-client"
    owner: root
  become: true

- name: Generate all nested env files for the service
  include: "env-files.yml"

- name: Start the docker-compose service
  command: "docker-compose -f /etc/docker-compose/{{ client_data.name}}/docker-compose.yml up -d"
  become: true